version: '3'

services:
  rasa:
    image: rasa/rasa_nlu:latest-full
    ports:
      - 5000:5000

  deeppavlov:
    image: deeppavlov0.0.8-buster
    command: python3 -m deeppavlov riseapi ./intents_snips.json
    ports:
    - 5001:5000