version: '3.2'


services:
  rasa-tensorflow:
    image: rasa/rasa_nlu:latest-tensorflow  # TODO: Give fixed version if possible
    ports:
    - 5000:5000

  rasa-spacy:
    image: rasa/rasa_nlu:0.13.7-spacy
    ports:
      - 5001:5000

  rasa-mitie:
    image: rasa/rasa_nlu:0.13.7-mitie
    ports:
      - 5002:5000

  deeppavlov-snips:
    image: deeppavlov0.0.8-buster
    command: python3 -m deeppavlov riseapi ./intents_snips.json
    ports:
      - 5003:5000

  deeppavlov-dcts2_webapplications:
    image: deeppavlov0.0.8-buster
    volumes:
      - ./systems/deeppavlov/configs:/var
    command: python3 -m deeppavlov riseapi /var/intents_dcts2_webapplications.json
    ports:
      - 5004:5000
