version: '2'

services:
  rasa:
    image: rasa/rasa_nlu:latest-full
    ports:
      - 5000:5000

  deeppavlov:
    build: "./deeppavlov"

  deeppavlov-intents-snips:
    extends: "deeppavlov"
    command: "python -m deeppavlov install ./intents_snips.json"
      #&& \
      #        python -m deeppavlov download ./intents_snips.json && \
      #        python -m deeppavlov riseapi"
    ports:
      - 5001:5000