version: '3.2'


services:
  rasa-tensorflow:
    image: rasa/rasa_nlu:0.13.8-tensorflow
    ports:
    - 5000:5000

  rasa-spacy:
    image: rasa/rasa_nlu:0.13.8-spacy
    ports:
      - 5001:5000

  rasa-mitie:
    image: rasa/rasa_nlu:0.13.8-mitie
    ports:
      - 5002:5000
