version: '3.2'


services:
  rasa:
    image: rasa/rasa_nlu:latest-full
    ports:
      - 5000:5000

  deeppavlov-snips:
    image: deeppavlov0.0.8-buster
    command: python3 -m deeppavlov riseapi ./intents_snips.json
    ports:
    - 5001:5000

  deeppavlov-dcts2_webapplications:
    image: deeppavlov0.0.8-buster
    volumes:
    - ./deeppavlov/configs:/var
    command: python3 -m deeppavlov riseapi /var/intents_dcts2_webapplications.json
    ports:
    - 5002:5000